### ISSUE TITLE
TODO 

### ISSUE THREAD

**Issue by lgatto** [lgatto/rpx#9]
- [x] document new project caching
- [x] function to query cache for rpx resources
      - get cached projects
      - delete cached projects
- [x] test error with non-unique rpx resources
- [x] cite ppx in README
